### ISSUE TITLE
How to get the Device ID

### ISSUE THREAD

**Issue by moizsami** [fadilsiddique/frappe_fcm_notification#1]
Hi,

I am fairly new to this, but was really interested in this App. Wanted to know in your guide you mentioned to get the device ID and add it to the user device doctype. But how to get the device ID? can you please explain that part aswell.

Thanks

**Comment by usman8786** [comment]
> Hi,
> 
> I am fairly new to this, but was really interested in this App. Wanted to know in your guide you mentioned to get the device ID and add it to the user device doctype. But how to get the device ID? can you please explain that part aswell.
> 
> Thanks

Same here. I even reached out to him on LinkedIn, asking for more help with registering the Device Token and storing it. He said he will update it.

**Comment by fadilsiddique** [comment]
> Hi,
> 
> I am fairly new to this, but was really interested in this App. Wanted to know in your guide you mentioned to get the device ID and add it to the user device doctype. But how to get the device ID? can you please explain that part aswell.
> 
> Thanks


The device token is generated on the client side using Firebase Cloud Messaging (FCM) SDK in your mobile or web application. When the user logs in or launches the app, the frontend retrieves this unique token and sends it to your backend and store via User device Doctype API (/api/resource/User Device), associating it with the user id.

**Comment by volkswagner** [comment]
> > Hi,
> > I am fairly new to this, but was really interested in this App. Wanted to know in your guide you mentioned to get the device ID and add it to the user device doctype. But how to get the device ID? can you please explain that part aswell.
> > Thanks
> 
> The device token is generated on the client side using Firebase Cloud Messaging (FCM) SDK in your mobile or web application. When the user logs in or launches the app, the frontend retrieves this unique token and sends it to your backend and store via User device Doctype API (/api/resource/User Device), associating it with the user id.

I still don't understand this. Does the Frappe HR PWA have this capability? If not, how can we retrieve the device ID?
